/**
 * Image upload & thumbnail tests
 *
 * Run with:
 *   TEST_BASE_URL=http://localhost:5176 node --test test/image-upload.test.mjs
 *
 * Verifies:
 *   1. Upload returns a path with ?t= cache-buster
 *   2. The raw image file is written to disk
 *   3. Thumbnail is served (and is webp) after upload
 *   4. Re-uploading the same breed regenerates a different thumbnail
 *   5. PATCH /api/breeds/:id strips ?t= before saving to DB
 *   6. PUT /api/myherd strips ?t= from all imageUrls before saving
 *   7. /api/thumb returns 404 for unknown images
 *   8. /api/thumb blocks path traversal
 *   9. Upload requires authentication
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';

// ── Helpers ───────────────────────────────────────────────────────────────────
let baseUrl;
let firstBreedId;
let testRunId;
let testIdx = 0; // incremented per call to nextName() → each sub-test gets its own file      // unique per test run → unique filenames → no cross-run lock issues
let RED_DATA_URL;   // valid JPEG generated by sharp
let BLUE_DATA_URL;  // valid JPEG (different color) generated by sharp

// Each call produces a unique breed name so every sub-test gets its own image file
function nextName() { return `TestRun${testRunId}_${++testIdx}`; }

async function buildTestImages() {
  // Use sharp (already a HerdHub dependency) to create guaranteed-valid images
  const { default: sharp } = await import('sharp');
  const redBuf  = await sharp({ create: { width: 10, height: 10, channels: 3, background: { r: 255, g: 0,   b: 0   } } }).jpeg().toBuffer();
  const blueBuf = await sharp({ create: { width: 10, height: 10, channels: 3, background: { r: 0,   g: 0,   b: 255 } } }).jpeg().toBuffer();
  RED_DATA_URL  = `data:image/jpeg;base64,${redBuf.toString('base64')}`;
  BLUE_DATA_URL = `data:image/jpeg;base64,${blueBuf.toString('base64')}`;
}

async function getFirstBreedId() { /* kept for potential future use */ }


// ── HTTP helpers ──────────────────────────────────────────────────────────────
async function post(url, body, headers = {}) {
  const r = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify(body),
  });
  return r;
}

// Credentials from env vars; defaults to the seeded HerdHub admin
const ADMIN_EMAIL    = process.env.TEST_ADMIN_EMAIL    ?? 'pauldenhertog256@gmail.com';
const ADMIN_PASSWORD = process.env.TEST_ADMIN_PASSWORD ?? 'PipoPassword*';

async function login(email = ADMIN_EMAIL, password = ADMIN_PASSWORD) {
  const r = await post(`${baseUrl}/api/login`, { email, password });
  const data = await r.json();
  assert.equal(r.status, 200, `Login failed: ${JSON.stringify(data)}`);
  const setCookie = r.headers.get('set-cookie');
  return setCookie.split(';')[0]; // session=...
}

// Register + login a fresh user for non-admin tests
async function registerAndLoginUser(email, password = 'TestPass123!') {
  await post(`${baseUrl}/api/register`, { email, password }).catch(() => {/* ignore if already exists */});
  return login(email, password);
}

// ─────────────────────────────────────────────────────────────────────────────
// All subtests run sequentially because each `await t.test(...)` call blocks
// until the previous one completes. This prevents file-lock races on Windows
// where sharp holds the image file open while generating a thumbnail.
// ─────────────────────────────────────────────────────────────────────────────

test('image upload & thumbnail', { skip: !process.env.TEST_BASE_URL }, async (t) => {
  baseUrl = process.env.TEST_BASE_URL;
  testRunId = Date.now();
  await buildTestImages();
  const breeds = await (await fetch(`${baseUrl}/api/breeds`)).json();
  assert.ok(Array.isArray(breeds) && breeds.length > 0, 'No breeds in DB');
  firstBreedId = breeds[0].id;

  await t.test('upload returns path with ?t= cache-buster', async () => {
    const name = nextName();
    const ck = await login();
    const r = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(r.status, 200, `Expected 200, got ${r.status}`);
    const { path: imgPath } = await r.json();
    assert.ok(imgPath?.startsWith('/images/'), `path should start with /images/, got: ${imgPath}`);
    assert.ok(imgPath.includes('?t='), `path should contain ?t= cache-buster, got: ${imgPath}`);
  });

  await t.test('image file is written to disk', async () => {
    const name = nextName();
    const ck = await login();
    const r = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(r.status, 200, `Upload returned ${r.status}`);
    const { path: imgPath } = await r.json();
    const imgUrl = `${baseUrl}${imgPath.split('?')[0]}`;
    const imgRes = await fetch(imgUrl);
    assert.equal(imgRes.status, 200, `Image file not served at ${imgUrl}`);
  });

  await t.test('thumbnail is served (webp) immediately after upload', async () => {
    const name = nextName();
    const ck = await login();
    const r = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(r.status, 200, `Upload returned ${r.status}`);
    const { path: imgPath } = await r.json();
    const filename = imgPath.split('?')[0].replace('/images/', '');
    const thumbRes = await fetch(`${baseUrl}/api/thumb/${filename}`);
    assert.equal(thumbRes.status, 200, `Thumb not available: ${thumbRes.status}`);
    assert.equal(thumbRes.headers.get('content-type'), 'image/webp', 'Thumb should be webp');
  });

  await t.test('re-upload regenerates a different thumbnail', async () => {
    // Both uploads use the SAME name so they target the same file (testing re-upload)
    const name = nextName();
    const ck = await login();
    const r1 = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(r1.status, 200, `First upload returned ${r1.status}`);
    const { path: p1 } = await r1.json();
    const filename = p1.split('?')[0].replace('/images/', '');
    const thumb1 = Buffer.from(await (await fetch(`${baseUrl}/api/thumb/${filename}`)).arrayBuffer());

    const r2 = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: BLUE_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(r2.status, 200, `Second upload returned ${r2.status}`);
    const { path: p2 } = await r2.json();
    assert.ok(p2.includes('?t='), 'Second upload should return cache-buster');
    const thumb2 = Buffer.from(await (await fetch(`${baseUrl}/api/thumb/${filename}`)).arrayBuffer());
    assert.notDeepEqual(thumb1, thumb2, 'Thumbnail should change after re-upload');
  });

  await t.test('PATCH breed strips ?t= from imageUrl before saving', async () => {
    const name = nextName();
    const ck = await login();
    const upR = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' },
      { Cookie: ck });
    assert.equal(upR.status, 200, `Upload returned ${upR.status}`);
    const { path: imgPath } = await upR.json();
    assert.ok(imgPath.includes('?t='));

    const patchR = await fetch(`${baseUrl}/api/breeds/${firstBreedId}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Cookie: ck },
      body: JSON.stringify({ imageUrl: imgPath }),
    });
    assert.equal(patchR.status, 200);
    const breed = await patchR.json();
    assert.ok(!breed.imageUrl.includes('?'), `Saved imageUrl should not contain ?t=, got: ${breed.imageUrl}`);
  });

  await t.test('PUT myherd strips ?t= from all imageUrls before saving', async () => {
    const userCk = await registerAndLoginUser(`testuser_${Date.now()}@test.invalid`);
    const fakeHerd = [{ id: 99, name: 'MyBreed', imageUrl: '/images/99_mybreed_1.jpg?t=1234567890' }];
    const r = await fetch(`${baseUrl}/api/myherd`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', Cookie: userCk },
      body: JSON.stringify(fakeHerd),
    });
    assert.equal(r.status, 200);
    const herd = await (await fetch(`${baseUrl}/api/myherd`, { headers: { Cookie: userCk } })).json();
    const saved = herd.find((b) => b.id === 99);
    assert.ok(saved, 'breed should be in herd after PUT');
    assert.ok(!saved.imageUrl.includes('?'), `Saved imageUrl should not contain ?t=, got: ${saved.imageUrl}`);
  });

  await t.test('thumb returns 404 for unknown image', async () => {
    const r = await fetch(`${baseUrl}/api/thumb/nonexistent_file.jpg`);
    assert.equal(r.status, 404);
  });

  await t.test('thumb blocks path traversal', async () => {
    const url = new URL(baseUrl);
    const status = await new Promise((resolve, reject) => {
      const req = http.request(
        { host: url.hostname, port: Number(url.port) || 80, path: '/api/thumb/../../etc/passwd', method: 'GET' },
        (res) => { resolve(res.statusCode); res.resume(); },
      );
      req.on('error', reject);
      req.end();
    });
    assert.ok([400, 404].includes(status), `Expected 400 or 404, got ${status}`);
  });

  await t.test('upload requires login', async () => {
    const name = nextName();
    const r = await post(`${baseUrl}/api/upload-image`,
      { name, breedId: firstBreedId, dataUrl: RED_DATA_URL, context: 'master' });
    assert.equal(r.status, 401);
  });
});

